version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8089:8089
    environment:
      - DOCKER_API_VERSION=1.39
