version: "3.9"
services:
  app:
    container_name: tdcm
    image: ghcr.io/davedean/tdcm:main
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8089:8089
    environment:
      - DOCKER_API_VERSION=1.39
      - USER_AUTH=true
      - USER=admin
      - PASS=admin
